// Dataset registry seeds — placeholder slots for the data to come, declared
// ahead of the actual feeds so every mandate already knows what it will run on.
// 'live' datasets ride the heartbeat's connector cadence; 'expected' ones are
// the founder's staging list. Company-wide (no persona), like businessdata.js.

const NOW = Date.now();
const hoursAgo = (h) => new Date(NOW - h * 3600e3).toISOString();

export const datasetsSeed = {
  fmcg: [
    {
      id: 'fmcg-ds-pos',
      name: 'POS sell-out — modern trade',
      description: 'Store-level sell-out by SKU and banner, all UAE/KSA key accounts.',
      source: 'Retailer portals + Nielsen feed',
      cadence: 'daily',
      status: 'live',
      rows: 412_083,
      columns: ['date', 'banner', 'store', 'sku', 'units', 'value_aed', 'osa_flag'],
      lastLoadAt: hoursAgo(0.4),
      feeds: ['On-shelf availability', 'Sell-in vs sell-out gap'],
      analysisIdeas: ['OSA by banner vs merchandiser routes', 'Promo sell-through vs trade calendar'],
    },
    {
      id: 'fmcg-ds-trade',
      name: 'Trade spend ledger',
      description: 'Accruals, claims and settlements by customer and promo.',
      source: 'Anaplan — FY26 Operating Plan',
      cadence: 'weekly',
      status: 'live',
      rows: 58_411,
      columns: ['week', 'customer', 'promo_id', 'accrual_aed', 'claim_aed', 'settled_aed'],
      lastLoadAt: hoursAgo(3),
      feeds: ['Trade-spend ROI', 'Trade spend % of revenue'],
      analysisIdeas: ['Accrual vs promo-calendar drift (the Protein trade-spend finding)', 'Claims aging by distributor'],
    },
    {
      id: 'fmcg-ds-fill',
      name: 'Order-to-delivery extract (OTIF)',
      description: 'Order lines vs shipped vs delivered, per DC and customer.',
      source: 'SAP SD + WMS',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Case fill rate (OTIF)', 'Inventory days'],
      analysisIdeas: ['Fill-rate bridge: stock vs slotting vs transport misses', 'Key-account penalty exposure at current fill'],
    },
    {
      id: 'fmcg-ds-oee',
      name: 'Plant historian — line OEE',
      description: 'Minute-level line states, speeds and scrap counters, 6 plants.',
      source: 'OSIsoft PI historian',
      cadence: 'hourly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['OEE', 'Waste & scrap', 'First-pass yield'],
      analysisIdeas: ['Yield masked by rework (breaded-chicken finding)', 'Changeover time by SKU family'],
    },
    {
      id: 'fmcg-ds-ar',
      name: 'Receivables aging',
      description: 'Open AR by customer, entity and bucket, with terms.',
      source: 'SAP FI',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Working-capital days'],
      analysisIdeas: ['DSO drift vs terms (Carrefour 74d finding)', 'Egypt book re-alert threshold tuning'],
    },
    {
      id: 'fmcg-ds-hr',
      name: 'Workforce roster & attrition',
      description: 'Headcount, joiners/leavers and shift coverage by site.',
      source: 'HR services — SuccessFactors',
      cadence: 'weekly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Frontline attrition'],
      analysisIdeas: ['Attrition → fill-rate compounding (ties to the hero finding)'],
    },
  ],
  healthcare: [
    {
      id: 'hc-ds-claims',
      name: 'Claims 835/837 feed',
      description: 'Submitted claims and remittances from the clearinghouse.',
      source: 'Clearinghouse SFTP',
      cadence: 'daily',
      status: 'live',
      rows: 96_120,
      columns: ['claim_id', 'payer', 'facility', 'billed', 'allowed', 'denied_code'],
      lastLoadAt: hoursAgo(1),
      feeds: ['Claim denial rate', 'Clean claim rate'],
      analysisIdeas: ['Denial surge by payer and code', 'Registration-error recurrence after the checklist fix'],
    },
    {
      id: 'hc-ds-adt',
      name: 'ADT census feed',
      description: 'Admissions, discharges, transfers — bed states by unit.',
      source: 'HL7 interface engine',
      cadence: 'hourly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Average length of stay', 'Bed occupancy'],
      analysisIdeas: ['Discharge-delay drivers by ward', 'ALOS → premium-pay conversion'],
    },
    {
      id: 'hc-ds-or',
      name: 'OR schedule & utilization',
      description: 'Block schedules, case times and turnover, all sites.',
      source: 'Surgical scheduling system',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['OR utilization'],
      analysisIdeas: ['Block-release behavior after the Lakeside rule change'],
    },
  ],
  manufacturing: [
    {
      id: 'mfg-ds-mes',
      name: 'MES line telemetry',
      description: 'Counts, rates, stop reasons and changeover events by line, both plants.',
      source: 'MES historian',
      cadence: 'streaming',
      status: 'live',
      rows: 1284403,
      columns: ['ts', 'plant', 'line', 'state', 'rate', 'stop_reason', 'good_count', 'scrap_count'],
      lastLoadAt: new Date(Date.now() - 9 * 60e3).toISOString(),
      feeds: ['OEE', 'Throughput attainment', 'Scrap rate', 'Changeover time'],
      analysisIdeas: ['Stop-reason Pareto on the constraint line', 'Changeover duration by crew and shift'],
    },
    {
      id: 'mfg-ds-cmms',
      name: 'CMMS work orders',
      description: 'Planned and reactive maintenance orders, PM compliance and downtime causes.',
      source: 'CMMS export',
      cadence: 'daily',
      status: 'live',
      rows: 48211,
      columns: ['order_id', 'asset', 'type', 'planned_date', 'completed_date', 'downtime_h', 'failure_mode'],
      lastLoadAt: new Date(Date.now() - 62 * 60e3).toISOString(),
      feeds: ['Unplanned downtime', 'PM compliance', 'MTTR'],
      analysisIdeas: ['PM compliance vs downtime on the constraint line', 'Failure-mode mix before and after the PM slide'],
    },
    {
      id: 'mfg-ds-erp',
      name: 'ERP purchasing & inventory',
      description: 'PO lines, receipts, supplier promise dates and stock positions.',
      source: 'ERP extract',
      cadence: 'daily',
      status: 'live',
      rows: 96520,
      columns: ['po_line', 'supplier', 'promise_date', 'receipt_date', 'qty', 'qty_rejected', 'stock_days'],
      lastLoadAt: new Date(Date.now() - 3 * 3600e3).toISOString(),
      feeds: ['Supplier OTIF', 'Raw material days', 'Cost variance vs standard', 'WIP days'],
      analysisIdeas: ['OTIF by supplier vs the two castings outliers', 'Safety-stock overrides vs stockout history'],
    },
    {
      id: 'mfg-ds-qms',
      name: 'QC inspection results',
      description: 'Incoming, in-process and final inspection outcomes with defect codes.',
      source: 'QMS API',
      cadence: 'daily',
      status: 'live',
      rows: 22174,
      columns: ['lot', 'stage', 'part_family', 'inspected', 'defects', 'defect_code', 'supplier'],
      lastLoadAt: new Date(Date.now() - 95 * 60e3).toISOString(),
      feeds: ['First-pass yield', 'Customer PPM', 'Inbound defect PPM'],
      analysisIdeas: ['B-housing scrap vs tooling refresh timeline', 'Casting defect codes by supplier lot'],
    },
    {
      id: 'mfg-ds-energy',
      name: 'Energy submeters',
      description: 'Utility submeters by line and area, 15-minute interval, both plants.',
      source: 'SCADA historian',
      cadence: 'streaming',
      status: 'live',
      rows: 508112,
      columns: ['ts', 'plant', 'meter', 'kwh', 'area'],
      lastLoadAt: new Date(Date.now() - 4 * 60e3).toISOString(),
      feeds: ['Energy per unit'],
      analysisIdeas: ['Baseload vs production-linked draw since the compressor swap'],
    },
    {
      id: 'mfg-ds-ehs',
      name: 'EHS incident log',
      description: 'Incidents, near misses and observation cards with severity and location.',
      source: 'EHS system',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Near-miss reporting', 'Lost-time incidents'],
      analysisIdeas: ['Reporting rate by shift since the Dammam restructure'],
    },
  ],
};
