// Dataset registry seeds — placeholder slots for the data to come, declared
// ahead of the actual feeds so every mandate already knows what it will run on.
// 'live' datasets ride the heartbeat's connector cadence; 'expected' ones are
// the founder's staging list. Company-wide (no persona), like businessdata.js.

const NOW = Date.now();
const hoursAgo = (h) => new Date(NOW - h * 3600e3).toISOString();

export const datasetsSeed = {
  fmcg: [
    {
      id: 'fmcg-ds-pos',
      name: 'POS sell-out — modern trade',
      description: 'Store-level sell-out by SKU and banner, all UAE/KSA key accounts.',
      source: 'Retailer portals + Nielsen feed',
      cadence: 'daily',
      status: 'live',
      rows: 412_083,
      columns: ['date', 'banner', 'store', 'sku', 'units', 'value_aed', 'osa_flag'],
      lastLoadAt: hoursAgo(0.4),
      feeds: ['On-shelf availability', 'Sell-in vs sell-out gap'],
      analysisIdeas: ['OSA by banner vs merchandiser routes', 'Promo sell-through vs trade calendar'],
    },
    {
      id: 'fmcg-ds-trade',
      name: 'Trade spend ledger',
      description: 'Accruals, claims and settlements by customer and promo.',
      source: 'Anaplan — FY26 Operating Plan',
      cadence: 'weekly',
      status: 'live',
      rows: 58_411,
      columns: ['week', 'customer', 'promo_id', 'accrual_aed', 'claim_aed', 'settled_aed'],
      lastLoadAt: hoursAgo(3),
      feeds: ['Trade-spend ROI', 'Trade spend % of revenue'],
      analysisIdeas: ['Accrual vs promo-calendar drift (the Protein trade-spend finding)', 'Claims aging by distributor'],
    },
    {
      id: 'fmcg-ds-fill',
      name: 'Order-to-delivery extract (OTIF)',
      description: 'Order lines vs shipped vs delivered, per DC and customer.',
      source: 'SAP SD + WMS',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Case fill rate (OTIF)', 'Inventory days'],
      analysisIdeas: ['Fill-rate bridge: stock vs slotting vs transport misses', 'Key-account penalty exposure at current fill'],
    },
    {
      id: 'fmcg-ds-oee',
      name: 'Plant historian — line OEE',
      description: 'Minute-level line states, speeds and scrap counters, 6 plants.',
      source: 'OSIsoft PI historian',
      cadence: 'hourly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['OEE', 'Waste & scrap', 'First-pass yield'],
      analysisIdeas: ['Yield masked by rework (breaded-chicken finding)', 'Changeover time by SKU family'],
    },
    {
      id: 'fmcg-ds-ar',
      name: 'Receivables aging',
      description: 'Open AR by customer, entity and bucket, with terms.',
      source: 'SAP FI',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Working-capital days'],
      analysisIdeas: ['DSO drift vs terms (Carrefour 74d finding)', 'Egypt book re-alert threshold tuning'],
    },
    {
      id: 'fmcg-ds-hr',
      name: 'Workforce roster & attrition',
      description: 'Headcount, joiners/leavers and shift coverage by site.',
      source: 'HR services — SuccessFactors',
      cadence: 'weekly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Frontline attrition'],
      analysisIdeas: ['Attrition → fill-rate compounding (ties to the hero finding)'],
    },
  ],
  healthcare: [
    {
      id: 'hc-ds-claims',
      name: 'Claims 835/837 feed',
      description: 'Submitted claims and remittances from the clearinghouse.',
      source: 'Clearinghouse SFTP',
      cadence: 'daily',
      status: 'live',
      rows: 96_120,
      columns: ['claim_id', 'payer', 'facility', 'billed', 'allowed', 'denied_code'],
      lastLoadAt: hoursAgo(1),
      feeds: ['Denial rate', 'Clean-claim rate'],
      analysisIdeas: ['Denial surge by payer and code', 'Registration-error recurrence after the checklist fix'],
    },
    {
      id: 'hc-ds-adt',
      name: 'ADT census feed',
      description: 'Admissions, discharges, transfers — bed states by unit.',
      source: 'HL7 interface engine',
      cadence: 'hourly',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['ALOS', 'Bed occupancy'],
      analysisIdeas: ['Discharge-delay drivers by ward', 'ALOS → premium-pay conversion'],
    },
    {
      id: 'hc-ds-or',
      name: 'OR schedule & utilization',
      description: 'Block schedules, case times and turnover, all sites.',
      source: 'Surgical scheduling system',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['OR utilization'],
      analysisIdeas: ['Block-release behavior after the Lakeside rule change'],
    },
  ],
  manufacturing: [
    {
      id: 'mfg-ds-cmms',
      name: 'CMMS work orders',
      description: 'Maintenance orders, PM compliance and downtime causes.',
      source: 'CMMS export',
      cadence: 'daily',
      status: 'expected',
      rows: null,
      columns: [],
      lastLoadAt: null,
      feeds: ['Unplanned downtime'],
      analysisIdeas: ['PM compliance vs downtime on the constraint line'],
    },
  ],
};
